language: php

dist: xenial

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  - sudo mysql -e 'create database homestead_test;'

php:
  - 7.2.1

services:
  - mysql

before_script:
  - cp .env.travis .env
  - cp phpunit.xml-travis phpunit.xml
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat storage/logs/*

cache:
  directories:
    - vendor

